# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Render Laporan

# Model Form Field configuration
form: $/yfktn/laporankependudukan/models/laporankependudukan/fieldsreport.yaml

# Model Class name
modelClass: Yfktn\LaporanKependudukan\Models\LaporanKependudukanReport

# Default redirect location
defaultRedirect: yfktn/laporankependudukan/renderlaporan

# Create page
create:
    title: backend::lang.form.create_title
    redirect: yfktn/laporankependudukan/renderlaporan/ini/:desaslug
    # redirectClose: yfktn/laporankependudukan/renderlaporan

# Update page
# update:
#     title: backend::lang.form.update_title
#     redirect: yfktn/laporankependudukan/renderlaporan
#     redirectClose: yfktn/laporankependudukan/renderlaporan

# Preview page
# preview:
#     title: backend::lang.form.preview_title
